
[tool.pyflow]
name = ""
py_version = "3.9"
version = "0.1.0"

[tool.pyflow.scripts]

[tool.pyflow.dependencies]
cffi = ">=0.0.0"
numpy = ">=0.0.0"
seaborn = ">=0.0.0"
matplotlib = ">=0.0.0"
minizinc = "^0.4.2"

[tool.pyflow.dev-dependencies]

